name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: azure/setup-helm@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "$GITHUB_TOKEN" | helm registry login ghcr.io --username=oauth-token --password-stdin
          helm package charts/gitlab-goproxy --version $GITHUB_REF_NAME
          
          echo "Creating chart release $GITHUB_REF_NAME"
          helm push "gitlab-goproxy-$GITHUB_REF_NAME.tgz" "oci://ghcr.io/$GITHUB_REPOSITORY/helm-charts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}